### ISSUE TITLE
What's the value in adding "Icon" to the name of every icon?

### ISSUE THREAD

**Issue by simonmcconnell** [rocketinsights/surface_heroicons#1]
Hi,

Tiny nitpick, but would you be open to removing the `Icon` suffix from the module names.  Unless there is a reason for it?

**Comment by jprincipe** [comment]
The reason is there are some icon names that would result in strange module names (i.e. `X` or `Map`).  Instead of picking out special cases to rename, I opted to just camel case each icon name and append `Icon` for consistency.

You always have the option to alias the icons you need at the top of your file with whatever name you like:

```elixir
alias Heroicons.Solid.ArchiveIcon, as: Archive

...

<Archive class="w-10 h-10/>
```

**Comment by simonmcconnell** [comment]
Righto. I don't see myself ever aliasing the icon modules and would've mimicked the names, but different strokes for different folks 😸
